# defining some url constants
base_w = "https://tekstowo.pl"
base = base_w + "/"
artist_songs = base + "piosenki_artysty,{},alfabetycznie,strona,0.html"
get_coments = base + "js,moreComments,S,{},{}"
get_replies = base + "js,showParent,{}"
artist_search = base + "szukaj,wykonawca,{},strona,1.html"
song_search = base + "szukaj,tytul,{},strona,1.html"
artist = base + "wykonawca,{}.html"
get_all_songs = base + "piosenki_artysty,{},alfabetycznie,strona,0.html"
login = base + "logowanie.html"
logout = base + "wyloguj.html"
